# Paths and directories
project_dir: "D:\\Uczelnia\\Thesis\\"
train_data_dir: "segmentation_data\\datasets\\train_valid\\"
test_data_dir: "segmentation_data\\datasets\\test\\"
train_annotations_dir: "segmentation_data\\train_annotations\\"
test_annotations_dir: "segmentation_data\\test_annotations\\"
pos_click_maps_dir: "pos_click\\"
neg_click_maps_dir: "neg_click\\"
test_image_path: "..\\utils\\test_image\\test_img.png"
models_dir: "..\\models\\"
tensorboard_logs_dir: "..\\models\\logs\\"

# Train parameters
batch_size: 2
epochs: 300
early_stop_patience: 20
train_val_ratio: 0.90
buffer_size: 234
seed: 42

# Data parameters
image_height: 512
image_width: 512
image_channels: 3
input_channels: 5
pos_click_map_scale: 2.0
neg_click_map_scale: 3.5

# Model architecture
shallow_unet: False
fcn: False
attention_dual_path: True

# GUI parameters
window_size: 1000
window_x: 700
window_y: 200
img_dpi: 300
