# Paths to data
PROJECT_PATH: "D:/Uczelnia/Thesis/"
DATA_PATH_TRAIN: "segmentation_data/datasets/train_valid/"
DATA_PATH_TEST: "segmentation_data/datasets/test/"
ANNOTATIONS_XML_TRAIN_PATH: "segmentation_data/train_annotations.xml"
ANNOTATIONS_XML_TEST_PATH: "segmentation_data/test_annotations.xml"
POS_CLICK_MAPS_PATH: "pos_click/"
NEG_CLICK_MAPS_PATH: "neg_click/"

# Paths to models
MODELS_PATH: "models/"
UNET_MODEL_PATH: "unet.hdf5"
UNET_DC_MODEL_PATH: "unet_dc.hdf5"
UNET_DP_MODEL_PATH: "unet_dp.hdf5"
TENSORBOARD_LOGS_PATH: "D:\\Uczelnia\\Thesis\\logs\\"

# Train parameters
BATCH_SIZE: 2
EPOCHS: 175
EARLY_STOP_PATIENCE: 15
TRAIN_RATIO: 0.90
VAL_RATIO: 0.1
BUFFER_SIZE: 128
SEED: 42

# Data parameters
IMAGE_HEIGHT: 512
IMAGE_WIDTH: 512
INPUT_CHANNELS: 5
POS_CLICK_MAP_SCALE: 2.0
NEG_CLICK_MAP_SCALE: 3.5

# Model parameters
MODELS: ["UNET_SHALLOW", "UNET_DC", "UNET_DP"]
UNET_SHALLOW: False
UNET_DC: False
UNET_DP: True
OPTIMIZER: "Adam"


