# Paths to data
DATA_PATH: "D:/DataScience/THESIS/Data/HPA_segmentation/segmentation_data/original/"
IMAGES_PATH_TRAIN: "D:/DataScience/THESIS/Data/HPA_segmentation/segmentation_data/train/image/"
MASKS_PATH_TRAIN: "D:/DataScience/THESIS/Data/HPA_segmentation/segmentation_data/train/mask/"
IMAGES_PATH_TEST: "D:/DataScience/THESIS/Data/HPA_segmentation/segmentation_data/test/"
CSV_PATH: "D:/DataScience/THESIS/Data/HPA_segmentation/prepared/data_csv.txt"
DATA_PATH_TRAIN: "D:/DataScience/THESIS/Data/HPA_segmentation/segmentation_data/train/"
DATA_PATH_TEST: "D:/DataScience/THESIS/Data/HPA_segmentation/segmentation_data/test_eval/"

# Paths to models
MODELS_PATH: "D:/DataScience/THESIS/models/"
UNET_MODEL_PATH: "unet.hdf5"
UNETPP_MODEL_PATH: "unet_pp.hdf5"
UNET_MOBILENET_MODEL_PATH: "unet_mobilenet.hdf5"
UNET_DC_MODEL_PATH: "unet_dc.hdf5"
TENSORBOARD_LOGS_PATH: "D:\\DataScience\\THESIS\\models\\logs\\"

# Train parameters
BATCH_SIZE: 1
EPOCHS: 500
EARLY_STOP_PATIENCE: 50
TRAIN_RATIO: 0.90
VAL_RATIO: 0.1
BUFFER_SIZE: 1024
SEED: 42

# Image parameters
IMAGE_HEIGHT: 512
IMAGE_WIDTH: 512
IMAGE_CHANNELS: 3

# Model parameters
MODELS: ["UNET_SHALLOW", "UNET_PP", "UNET_MOBILENET", "UNET_DC"]
UNET_SHALLOW: False
UNET_PP: False
UNET_MOBILENET: False
UNET_DC: True
OPTIMIZER: "Adam"